### ISSUE TITLE
Prosjektet må kunne kompileres og kjøres på windows-maskiner

### ISSUE THREAD

**Issue by kristandre** [kodeklubben/codeclub-viewer#113]

**Comment by NorwegianKiwi** [comment]
Ser ut som om problemet er at path.join gir en backslash på windows i stedet for en forward slash. Helt konkret, så er det linjen 
```
const publicPathWithoutSlash = path.join('/', subDir);
```
som gir publicPathWithoutSlash en verdi `\` i stedet for `/`, og dette fører til at lenkene i bl.a. index.html blir f.eks. "\/main.js" istedet for "/main.js"
