### ISSUE TITLE
Støtte for oppgaver på flere språk.

### ISSUE THREAD

**Issue by NorwegianKiwi** [kodeklubben/codeclub-viewer#125]
Se bl.a.
- https://github.com/arve0/codeclub_lesson_builder/issues/201
- https://github.com/kodeklubben/oppgaver/issues/170

Fra møtet torsdag 4.aug, 2016:
* Behold gui-valg på toppen. I tillegg kan vi legge til språkfilter (en ny gruppe på linje med "Operativsystemer" og "Tema") der gui-språket automatisk er valgt, og så kan man legge til så mange ekstra språk man vil.
* Filstruktur er fortrinnsvis på engelsk, men ikke viktig.
* Kun én oppgave per folder (må f.eks. dele opp 3d-flakser), én md-fil per språk.
* Tagge hver md-fil med språk (kategori "language")
* Fortrinnsvis begynne filnavn med to-bokstavs-språkkode og underscore, feks nb_straffespark.md og en_penalty_kick.md og nn_straffespark.md.
* Mulig vi må gjøre bokmål og nynorsk-flaggikonene skillbare (bokstaver på flagg?)
* Hvis man har valgt flere språk i filter, så skal playlistsiden vise alle språkalternativene, f.eks. bokser med tre versjoner av astrokatt.
* På lesson-siden kan det stå "Denne oppgaven er tilgjengelig på andre språk" (skrevet på gui-språket ditt), og gir en meny med alle språk oppgaven er tilgjengelig på.
* URL reflekterer filnavnene/path (som gjør det enklere å finne frem for oversettere). Dette vil også gjøre URL reflekterer lessonspråk (dersom man har lenke til lesson).
* Hvis man ikke har valgt flere språk, og en lesson mangler på det språket, ikke vis den lesson i playlist.
* Hvis man har valgt flere språk, og lesson finnes på hovedspråk, vis hovedspråk stort og de andre tilgjengelige språkene mindre (uten tag-ikoner).
* Hvis man har valgt flere språk og lesson ikke finnes på hovedspråk, vis hovedspråk-knapp stor men disablet og med teksten "ikke tilgjengelig på dette språk" (oversatt), og vis de andre tilgjengelig språkene mindre (uten tag-ikoner).
* Alle tags er laget på engelsk. Utvalget av disse tags er forhåndsbestemt (whitelistet) og forhåndsoversatt.

**Comment by Skagevang** [comment]
#309
