### ISSUE TITLE
Dele LessonItem i to kolonner i lærermodus. Tittel på venstre, veiledning høyre

### ISSUE THREAD

**Issue by kristandre** [kodeklubben/codeclub-viewer#127]
Oppgavelisten på playlistsidene: Lage oppgavene som tabell, 1. kolonne inneholder oppgavetekst + restriksjonsikoner, 2. kolonne inneholder knapp til veiledning i lærermodus. (Kolonnene skilles med skillestrek)

**Comment by NorwegianKiwi** [comment]
Er vi sikker på at vi vil ha det slik?

**Comment by agnetedjupvik** [comment]
Har dere landet på noe her, slik at vi kan vite om vi skal begynne å jobbe på det eller ikke?
