### ISSUE TITLE
Forslag forbedring for filter: Automatisk legg til tag "andre" i grupper uten tags

### ISSUE THREAD

**Issue by NorwegianKiwi** [kodeklubben/codeclub-viewer#135]
En lesson kan ha flere grupper med tags, f.eks. 'platform': ['linux', 'android']. Dersom en lesson mangler denne gruppen (evt at denne gruppen er tom), vil den ikke dukke opp selv om alle tags innenfor en gruppe er markert.

Forslaget er å (for hver lesson) automatisk legge til tag'en 'andre' i alle tomme eller ikke-eksisterende grupper. Dermed kan man velge 'andre' for å få opp alle lessons som ikke er markert med en tag i en gruppe.

**Comment by kristandre** [comment]
Bør vi da definere hvilke grupper/tags som er mulige å bruke først (i en config fil)?

**Comment by NorwegianKiwi** [comment]
Det kan jo være lurt, ellers må man jo først scanne gjennom alle oppgavene for å finne alle mulige tags, samt at det plutselig kan dukke opp andre grupper bare fordi noen har skrevet et gruppenavn feil i én oppgave.

Om ikke tags, så er det kanskje lurt å definere grupper ihvertfall. Og mtp denne issuen, så vil det holde, for da trenger vi bare legge til "andre" dersom en gruppe er tom eller ikke-eksisterende, men vi trenger ikke scanne gjennom alle oppgaver for å finne tags.

**Comment by kristandre** [comment]
Hvis vi har med tags også, så kan vi tillate flere måter å skrive samme taggen på.
F.eks:
```
iPhone/iPad (iOS): [ios, iphone, ipad, iphone/ipad, iphone/ipad(iOS), iphone/ipad (iOS)]
mac: [mac, osx, os x, macos, mac os]
```
Da vil `iPhone/iPad (iOS)` vises i filteret, og være knyttet til alle oppgaver som har en eller flere av `[ios, iphone, ipad, iphone/ipad, iphone/ipad(ios), iphone/ipad (ios)]`.

Eller blir dette bare forvirrende for de som skal tagge oppgaver?

**Comment by NorwegianKiwi** [comment]
Det siste her er vel mer "alias" av tags, og det kan vi godt diskutere, men det tror jeg blir en annen issue igjen. Her er det flere måter å gjøre det på, f.eks. si at alle tags som er i en array (slik du viser) blir automatisk omgjort til f.eks. "iPhone/iPad (iOS)". Men som sagt, synes dette virker som urelatert til dette issuet.

**Comment by NorwegianKiwi** [comment]
Jeg mener nå at gruppene og tags innenfor gruppene bør være definert i en config-fil, og grupper og tags som blir brukt som ikke står her, blir bare ignorert. Dette også for å gjøre oversettelse enklere.

**Comment by NorwegianKiwi** [comment]
Tags og grupper er nå definert i en config fil, lukker issue.
