### ISSUE TITLE
Build new website automatically on merge

### ISSUE THREAD

**Issue by NorwegianKiwi** [kodeklubben/codeclub-viewer#149]
Link to how it was done on old website:
https://github.com/arve0/codeclub_lesson_builder/blob/master/gulpfile.babel.js#L182

**Comment by arve0** [comment]
Also https://github.com/kodeklubben/oppgaver/blob/master/deploy.sh (should probably be written in js to achieve better error handling).

Current pitfalls / deficiencies:
1. The build machine needs a lot of memory. PDF-build eats memory. Make sure machine got swap.
2. Two repos trigger the build (oppgaver and cclb). Currently, both triggers a "changes" rebuild, touched/new .md files are built along with their PDFs. This works great for new lessons and fixes to existing lessons, but sometimes requires manual intervention when templates change (full rebuild).
3. Upon errors no-one is alerted, and we do not have a rutine for checking if the build succeeds (I check once in a while).

**Comment by NorwegianKiwi** [comment]
See Travis documentation: https://docs.travis-ci.com/user/deployment/pages/

**Comment by NorwegianKiwi** [comment]
Fixed for both codeclub-viewer (#574, #578, #579) and oppgave (https://github.com/kodeklubben/oppgaver/pull/938, https://github.com/kodeklubben/oppgaver/pull/941, https://github.com/kodeklubben/oppgaver/pull/942) repos.
