### ISSUE TITLE
Show course and lesson info

### ISSUE THREAD

**Issue by NorwegianKiwi** [kodeklubben/codeclub-viewer#150]
Show course-info and lesson-info, perhaps while hovering over courses (this is how it was done on the old website).

Links to where it was done in old website:
https://github.com/arve0/codeclub_lesson_builder/blob/master/scripts/course-hover.js
https://github.com/arve0/codeclub_lesson_builder/blob/master/scripts/lesson-hover.js

**Comment by kristandre** [comment]
Kan dette utsettes til en senere milestone, eller det viktig at dette er med i MVP?

**Comment by tjesi** [comment]
Denne kan utsettes.

Tjerand

2016-08-27 22:39 GMT+02:00 Kristoffer Ravik Andresen <
notifications@github.com>:

**Comment by Skagevang** [comment]
After meeting with Lance we agreed to only add hover to lessons. Picture inside tooltip are important and have a max length for text-file.
