### ISSUE TITLE
target=_blank is evil

### ISSUE THREAD

**Issue by arve0** [kodeklubben/codeclub-viewer#153]
Is using `target=_blank` a conscious choice for external courses / lessons?

https://css-tricks.com/use-target_blank/

**Comment by torkjels** [comment]
Har diskutert litt med Tjerand og Perry og vi kom fram til at når man klikker på slike linker fra oppgavesettet vil man også holde oppgavesettet oppe samtidig. Man vil både forbli på siden OG ha oppe den nye linken. Så vi tenker at target=_blank skal forbli på external :)

**Comment by arve0** [comment]
Hvorfor er dette ikke det samme for våre egne oppgaver? Åpne de også i nytt vindu?

**Comment by NorwegianKiwi** [comment]
Jeg har lest gjennom artikkelen som @arve0 postet først, og så en del av kommentarene under. Jeg er ikke helt enig i denne artikkelen fra 2014. For det første er dette en single page app, så hvis man forlater siden, så mister man all state (det gjør man jo ikke hvis man går til en intern oppgave). Dessuten antar artikkelen at folk vet hvordan man åpner en lenke i en ny tab. Det er det jo mange som ikke vet. Når vi i tillegg tydelig markerer de eksterne lenkene med et symbol slik at brukeren vet hva som kommer til å skje, så burde ikke dette være noe stort problem.

Nevner forøvrig at måde Twitter og Facebook bruker target="_blank" (ifølge den ene kommentaren, https://css-tricks.com/use-target_blank/#comment-1087629). Og gmail (https://css-tricks.com/use-target_blank/#comment-1087698).

Det er nok av kommentarer som er uenig med forfatteren, f.eks. https://css-tricks.com/use-target_blank/#comment-1087661
