### ISSUE TITLE
Lag plan og issues for å løse universell utforming

### ISSUE THREAD

**Issue by NorwegianKiwi** [kodeklubben/codeclub-viewer#158]
Sørg for at sidene er universelt utformet. Se f.eks. følgende lenker:
- https://uu.difi.no/
- https://egghead.io/courses/start-building-accessible-web-applications-today

Synes også vi skal vurdere å implementere mulighet for å slå på en font som hjelper de med dysleksi å lese:
- http://opendyslexic.org/
- https://github.com/antijingoist/open-dyslexic
- https://github.com/antijingoist/open-dyslexic/wiki/How-to:-Use-on-your-website

**Comment by Skagevang** [comment]
https://github.com/evcohen/eslint-plugin-jsx-a11y

**Comment by Skagevang** [comment]
Kanskje lukke dette issuet og dele opp i mindre issues?

**Comment by Skagevang** [comment]
Things to check manually 

- [ ] The page has a logical tab order
- [ ] Interactive controls are keyboard focusable
- [ ] The user's focus is directed to new content added to the page
- [ ] User focus is not accidentally trapped in a region
- [ ] Custom controls have associated labels
- [ ] Custom controls have ARIA roles
- [ ] Visual order on the page follows DOM order
- [ ] Offscreen content is hidden from assistive technology
- [ ] Headings don't skip levels
- [ ] HTML5 landmark elements are used to improve navigation
