### ISSUE TITLE
Mangler tester for getTags og getCourses

### ISSUE THREAD

**Issue by NorwegianKiwi** [kodeklubben/codeclub-viewer#16]
Mangler tester for
- [ ] getTests
- [ ] getCourses

**Comment by kristandre** [comment]
Disse funksjonene er avhengig av hvilke filer som finnes i lessonContext og iconContext. Har du tips til en måte disse kan testes på, uten å være avhengig av hva som finnes i `../oppgaver`?

**Comment by NorwegianKiwi** [comment]
Hva med å lage en folder under test som heter `oppgaver_mocks` (eller kanskje `testdata`?) der du kopierer inn noen få fake oppgaver, gjerne med litt kompliserte tags og annet snacks. Trenger ikke være så mange. Og så kan selve testen lage contextene den trenger fra disse? Evt kan det lages øverst i fila før alle testene, eller i test_helper eller en annen hjelpefil (contextCreator.js?) som ligger i `test/`- katalogen, og som du kan inkludere i testene.

Hva tror du?

**Comment by kristandre** [comment]
Å lage en folder med noen få fake oppgaver høres ut som en bra løsning

**Comment by arve0** [comment]
Da er det også lett å lage en funksjonstest med https://www.npmjs.com/package/assert-dir-equal

**Comment by NorwegianKiwi** [comment]
Gått ut på dato.
