### ISSUE TITLE
Større font

### ISSUE THREAD

**Issue by NorwegianKiwi** [kodeklubben/codeclub-viewer#160]
Fonten på dagens websider på lessons er 20px (så vidt jeg kan se). Synes vi skal fortsette med dette, samt at font-størrelsen på de andre sidene bør være tilsvarende store.

**Comment by arve0** [comment]
Font-størrelse burde justeres etter skjermstørrelse:

https://github.com/arve0/codeclub_lesson_builder/blob/master/styles/main.less#L21-L28
