### ISSUE TITLE
Flickering border on filter panel

### ISSUE THREAD

**Issue by NorwegianKiwi** [kodeklubben/codeclub-viewer#175]
On the playlist page, the right hand border flickers when resizing the window.

Note that this was done on a retina screen on a Macbook. I didn't see the flickering when I tried to resize the window on an external screen connected to the same Macbook.

![flickeringborder](https://cloud.githubusercontent.com/assets/8851134/21741857/85b37cf0-d4e2-11e6-90ec-93f7e67f929d.gif)

**Comment by OzKara** [comment]
Ingen i gruppa opplever dette problemet.

**Comment by agnetedjupvik** [comment]
Was not able to reproduce issue.

**Comment by NorwegianKiwi** [comment]
Cannot reproduce either.
