### ISSUE TITLE
Add margin to the teacher text box on front page in mobile mode

### ISSUE THREAD

**Issue by NorwegianKiwi** [kodeklubben/codeclub-viewer#178]
Open the front page. Go to teacher mode. Notice that the box with the "teacher text" has no margin. Add this.

**Comment by agnetedjupvik** [comment]
I'm not sure where this problem actually is. Are you talking about this box? 
<img width="434" alt="skjermbilde 2017-02-01 kl 10 42 15" src="https://cloud.githubusercontent.com/assets/10497878/22501956/35eec37c-e86b-11e6-89a4-d4e52bb21d56.png">

**Comment by tjesi** [comment]
Right now the text showing is in the code. We want this to be an own
document instead, so that it is easier to edit.

Den ons. 1. feb. 2017, 15:13 skrev Agnete Djupvik <notifications@github.com

**Comment by agnetedjupvik** [comment]
Aren't you referencing #121, @tjesi? I think this issue is about something else.

**Comment by tjesi** [comment]
Correct.

- Tjerand

.......................................
Tjerand A. Silde
(+47) 47301607
@TjerandSilde <http://instagram.com/tjerandsilde>
appear.in/tjesi
tjerandsilde.org

2017-02-17 11:24 GMT+01:00 Agnete Djupvik <notifications@github.com>:
