### ISSUE TITLE
Show real constraints in components/LessonList/LessonItem.js

### ISSUE THREAD

**Issue by NorwegianKiwi** [kodeklubben/codeclub-viewer#182]
Currently, the constraints that are shown are random, hardcoded mocks. Make them show the real constraints.

**Comment by NorwegianKiwi** [comment]
I don't think any of the courses or lessons have been tagged with constraints. I don't even think anybody has thought through how this would be done. Do we still think this is useful? And if yes, how would be the best way to implement and tag the lessons?

**Comment by Skagevang** [comment]
What do you want us to do here?

**Comment by NorwegianKiwi** [comment]
Before implementing anything, we need to find out if and how constraints should work.

Also, see this google docs for some comments/discussions: https://docs.google.com/document/d/1sStvlg2QNp7niYQfhVQOuSiV_m9gd70CIrjwicQKLAw/edit?usp=sharing

Note that this is related to how the filter works, and in fact I don't think that this is clearly defined either. Let me try to explain a few suggestions for "filter" (not talking about constraints yet).

(NOTE: When I write below that we need to tag courses/lessons, we usually only need to tag courses, and all the lessons of that course will inherit the tags. Only if there is a specific lesson in a course that has different tags, do we need to override them. So tagging "all courses/lessons" is not a huge job, as of now there are only 17 courses.)

OPTION 1) Clicking the checkbox for one of the "operativsystem" tags means that we show all courses/lessons that work for this operativsystem.
Consequences: Courses/lessons NOT marked with an operativsystem will not be shown, and if a new operativsystem-tag is introduced, then ALL courses/lessons must add this tag to be shown there. E.g. if you click "mac", then practically all courses/lessons except Kodu must be marked with "mac", and if new courses/lessons are added, these must also be marked with "mac". It will also be hard for the use to separate out the courses/lessons that ONLY work on a mac (like "swift"), but I don't know if that would be useful. The reverse is of course possible; clicking on "windows" will hide "swift" since it has "mac" but not "windows". What about "raspberry pi"? Should "scratch" have "raspberry pi"? I know it is possible to run scratch on a raspberry pi, but should that be included? And what about "uten datamaskin"? Should all courses have "uten datamaskin" (since you can do these lessons even if you have a computer)?

OPTION 2) Clicking the checkbox for one of the "operativsystem" tags means that we show courses/lessons that work only for this operativsystem, but no other. 
Consequences: We only need to tag the courses/lessons that are "mac only". But if the user clicks "mac", it will hide everything that is not "mac only", even if it works for a mac. This seems counter intuitive. On the other hand, clicking "uten datamaskin", you probably only want the lessons you can do without a computer. Now, we have been talking about adding a "other" tag in each group, which are all the remaining lessons that do not have a tag, but we probably still want to add a "uten datamskin" tag.

It is not clear to me which option is best, but I am leaning towards (1).

So, what about constraints, the icons that are shown on the lessons (and perhaps courses)? Should they have anything to do with filter? Should they f.ex. show the information in (2), i.e. that "this course/lesson works ONLY on a mac"? That way, if an apple-icon (if that is the icon for macs) showed up on a lesson, and you are on a windows machine, it would be a hint to you that you should click the "windows" filter to hide them. Or the "costs money" icon could be on the ones that are not free (but then we probably would need a "free" tag in the filter).

First question is if we need the constraints. Secondly, how do we mark the courses/lessons with constraints? You could find "mac only" from the filter tags by marking everything EXCEPT "mac" and then invert that selection (i.e. take all courses/lessons and subtract the ones shown when clicking everything except "mac"). That way we wouldn't need mark all courses/lessons with both filter tags and constraints. Perhaps we should only mark the constraints (i.e. "mac only", "windows only", "costs money"), and calculate the filter tags from them ("mac"=everything that works on mac, "windows"=everything that works on windows, "free").

So, how should filters and constraints work? How do we mark the courses/lessons without entering information twice, keeping it intuitive for the user and making it as simple as possible for people creating courses/lessons?

**Comment by agnetedjupvik** [comment]
The bachelor group and Lance discussed this thoroughly. We arrived on the conclusion that we shouldn't make these kinds of decisions without doing more proper research on what our users want. Currently, we can't be sure that constraints are something that the user needs.

Our plan to arrive at a final conclusion: 
- Change the name from "Operativsystem" to "Utstyr" throughout the site to make it easier to understand for the kids
- The bachelor group will attend Kodeklubben events and try to understand how filters are used by users of different ages and skill levels

If the need shows for this at coding nights, we'll readress this issue and implement constraints that our users want. Until then we will work on improving the filter and see if that is sufficient to convey the information we want to get across.
