### ISSUE TITLE
Checkboxes for each subtask in a lesson

### ISSUE THREAD

**Issue by agnetedjupvik** [kodeklubben/codeclub-viewer#218]
In a lesson, there are many subtasks. All of them are represented with an empty white box. The user should be able to check the box when a task is completed.

<img width="776" alt="skjermbilde 2017-03-10 kl 14 46 32" src="https://cloud.githubusercontent.com/assets/10497878/23797483/63a25f48-05a0-11e7-8a20-abbf211cd1c9.png">

The checking of a box should store in LocalStorage that the task has been completed. If the box is unchecked, this should also update LocalStorage.

**Comment by arve0** [comment]
Any overall strategy on persistent storage? Have [localForage](https://github.com/localForage/localForage) been discussed?

**Comment by agnetedjupvik** [comment]
We're going to be using regular LocalStorage as of now, @arve0, and it seems to be fitting our needs for the time being.
