### ISSUE TITLE
"Report problem" button - improve new issue

### ISSUE THREAD

**Issue by arve0** [kodeklubben/codeclub-viewer#254]
Like this [example](https://github.com/kodeklubben/oppgaver/issues/new?title=Problem%20med%20Swift:%20Hei%20verden&body=Oppgavens%20kildekode:%20https://github.com/kodeklubben/oppgaver/tree/master/src/swift/hei_verden%0AOppgave:%20http://oppgaver.kidsakoder.no/swift/hei_verden/hei_verden.html%0A%0ABeskriv%20ditt%20problem%20her.%20Ta%20gjerne%20med%20operativsystem,%20nettleser%20og%20eventuell%20kode%20du%20har%20skrevet.), which adds a brief explanation of what should be contained in the report (reports has historically been shallow with the old text), and also links to source and lesson (to be more explicit of what is the issue).

**Comment by krskog** [comment]
La inn en [commit](https://github.com/kodeklubben/codeclub-viewer/pull/253/commits/e42c2097341121c9b3d9092616bfd4235b238e8b) som fikser dette i PR #253 :+1:

**Comment by NorwegianKiwi** [comment]
What @krskog said :)
