### ISSUE TITLE
scratch blocks looses their background-color on back-button

### ISSUE THREAD

**Issue by arve0** [kodeklubben/codeclub-viewer#255]
OSX Safari:

![scratch black background](https://cloud.githubusercontent.com/assets/4810521/26267273/87461982-3ce9-11e7-8580-3ef7edef5499.gif)

Strangely enough, it happens the _second_ time one goes back, not the first. Race condition?

**Comment by Skagevang** [comment]
https://github.com/scratchblocks/scratchblocks/issues/183
