### ISSUE TITLE
lesson index: jump to level does not work

### ISSUE THREAD

**Issue by arve0** [kodeklubben/codeclub-viewer#260]
These buttons does not do anything for me:

![skjermbilde 2017-05-20 kl 00 28 58](https://cloud.githubusercontent.com/assets/4810521/26269128/5ac9f20c-3cf3-11e7-9043-35e755119665.png)

Safari 10.1 OS X

![jump_to_level](https://cloud.githubusercontent.com/assets/4810521/26269183/81710922-3cf3-11e7-8ed4-056f8443394f.gif)

**Comment by Skagevang** [comment]
Same with Microsoft Edge 40.15063

Works in Google Chrome 58 and Internet Explorer 11.296

**Comment by Skagevang** [comment]
Works on Edge locally

**Comment by Skagevang** [comment]
Do not work in mobile mode either

**Comment by Skagevang** [comment]
Disappears if there is 15 lessons or less left on course page

**Comment by Skagevang** [comment]
See #360
