### ISSUE TITLE
Search Engine Optimization

### ISSUE THREAD

**Issue by arve0** [kodeklubben/codeclub-viewer#261]
Currently google finds the pages, but titles and excerpts are not good:

![skjermbilde 2017-05-20 kl 12 37 37](https://cloud.githubusercontent.com/assets/4810521/26275091/2707903a-3d59-11e7-9039-44fa9d64447f.png)

compared to root oppgaver.kidsakoder.no:

![skjermbilde 2017-05-20 kl 12 38 44](https://cloud.githubusercontent.com/assets/4810521/26275099/4a42022e-3d59-11e7-908b-2e498dc0e7c9.png)

**Comment by arve0** [comment]
Does #328 fix excerpts?

**Comment by arve0** [comment]
Excerpts still not fixed:

![skjermbilde 2017-07-28 kl 08 24 39](https://user-images.githubusercontent.com/4810521/28705049-4756aed4-736e-11e7-8d13-c961a5d3e5a1.png)

Reopening.

**Comment by Skagevang** [comment]
What about adding `<meta name="description" content="Introduction in lesson">` and "Introduction in lesson" are the start of index.md for that course?

**Comment by Skagevang** [comment]
Use this: https://www.npmjs.com/package/react-document-meta
Instead of DocumentTitle?

**Comment by NorwegianKiwi** [comment]
Dette har nå blitt oppdatert hos google etter at det var fikset hos oss.
