### ISSUE TITLE
Translate captions to Norwegian Nynorsk

### ISSUE THREAD

**Issue by krskog** [kodeklubben/codeclub-viewer#263]
Translate the captions in [captions_nn](https://github.com/kodeklubben/codeclub-viewer/blob/master/src/constants/captions_nn.js) from Norwegian to Norwegian Nynorsk. 

Example in English: [captions_en](https://github.com/kodeklubben/codeclub-viewer/blob/master/src/constants/captions_en.js)

**Comment by steinoro** [comment]
La inn forslag og [PR](https://github.com/kodeklubben/codeclub-viewer/pull/302) på den no.
