### ISSUE TITLE
Translate captions to Swedish

### ISSUE THREAD

**Issue by krskog** [kodeklubben/codeclub-viewer#264]
Translate the captions in [captions_sv](https://github.com/kodeklubben/codeclub-viewer/blob/master/src/constants/captions_sv.js) from Norwegian to Swedish. 

Example in English: [captions_en](https://github.com/kodeklubben/codeclub-viewer/blob/master/src/constants/captions_en.js)

**Comment by tjesi** [comment]
As we pr now don't have any projects in Swedish, we do this translation later. Not important to be a part of MVP.

**Comment by NorwegianKiwi** [comment]
Closing issue for now, create new when needed.
