### ISSUE TITLE
Translate captions to Danish

### ISSUE THREAD

**Issue by krskog** [kodeklubben/codeclub-viewer#265]
Translate the captions in [captions_da](https://github.com/kodeklubben/codeclub-viewer/blob/master/src/constants/captions_da.js) from Norwegian to Danish. 

Example in English: [captions_en](https://github.com/kodeklubben/codeclub-viewer/blob/master/src/constants/captions_en.js)

**Comment by tjesi** [comment]
As we pr now don't have any projects in Danish, we do this translation later. Not important to be a part of MVP.

**Comment by NorwegianKiwi** [comment]
Closing issue for now, create new when needed.
