### ISSUE TITLE
Show message if user changes language when inside a lesson

### ISSUE THREAD

**Issue by Skagevang** [kodeklubben/codeclub-viewer#280]
Right now, nothing happens if I change language when im inside a lesson. If that happens, I think the easiest way is to just show a message that says something like: This language is not supported for this lesson.

Other solutions is giving the user different choices. Like the same message over, but buttons that send the user back to the previous language or send them to frontpage/playlistpage to see other courses/lessons in that language. Or the same message and the improve page box, so they can translate the other lesson by them self.

I'm leaning towards the first one. Then the user only needs to change language or go to the page he wants.

**Comment by krskog** [comment]
Agree with the first one, atleast for now. A future add on should be to somehow "highlight"/show the languages the lesson is available in (or darken the languages the lesson is not available in), but I don't think that more functionality then showing a message is minimal viable product.

**Comment by NorwegianKiwi** [comment]
I also agree that the first one seems good for now.

@Skagevang, why don't you make a second issue with the follow-up suggestions that you and @krskog mention?

**Comment by Skagevang** [comment]
See #287

**Comment by Skagevang** [comment]
If user get a link (or write the URL himself) but the language in state is different from the language in lesson, the user should still see the lesson

Lessons should never cahnge the language in state

**Comment by NorwegianKiwi** [comment]
Suggestion: If you are seeing a lesson in a different language than you main gui-language, add a button beneath the title (where "lærerveileding" and "clear checkboxes" is today) that will take you to the same lesson in the language you have chosen for the gui.
