### ISSUE TITLE
Translate filter

### ISSUE THREAD

**Issue by Skagevang** [kodeklubben/codeclub-viewer#281]
See [README.md in oppgaverepo](https://github.com/kodeklubben/oppgaver/issues/380)

I still think that filtergroups and filtertags should be specified from the beginning. It takes 5 min to add a new filtergroup or filtertag in codeclub-viewer. And to my understanding this is rare.

**Comment by NorwegianKiwi** [comment]
I know I have changed my mind several times (and I might still change it again), but right now I think we should define the tags in the oppgave-repo, and also add captions that are shown in the gui (e.g. one file per language) for each tag. To make it simple, we should probably just define the tags (that are allowed in the lessons) in one language, either english or bokmål.

**Comment by Skagevang** [comment]
See [OppgaveRepoIssue](https://github.com/kodeklubben/oppgaver/issues/410)

**Comment by Skagevang** [comment]
#309
