### ISSUE TITLE
Change view on playlistpage

### ISSUE THREAD

**Issue by Skagevang** [kodeklubben/codeclub-viewer#282]
When one language is choosen in filter on playlistpage, the layout should stay as it is. But if multiple languages is choosen my proposal is this:
- Put a flag behind lesson title
- Keep mainlanguage as it was, regarding fontsize etc
- Equal lessons that's in a different language stays under the same lesson, but with a smaller fontsize. (In the same "box")

**Comment by NorwegianKiwi** [comment]
I agree.

In addition, when multiple languages are selected :
* perhaps add flags for the smaller titles too?
* how/if do you display lessons that don't exist for main language, but only for the other languages you have selected?

**Comment by Skagevang** [comment]
I agree with having flags for smaller titles too. 
If it exists lessons on other languages than main language, these lessons should be shown as well, but in smaller font. The place where lesson for mainlanguage should have been, should just be "removed"

**Comment by NorwegianKiwi** [comment]
Some thoughts on a use case for checking more than one language in filter: The user knows more than one language, and knows that not all lessons exist in their main language. E.g. an English person knows Norwegian, but prefers English. So she wants her lessons in English if possible, but if they only exist in Norwegian, she wants those.

Based on this use case, the first suggestion (call it suggestion A) is as follows:
(A) Just display the lessons in the main language if it exists in this language, or in one of the other languages if they only exist there. We wouldn't really need to show which languages they were available in.

But, what if the user has chosen English as main, and checked bokmål and nynorsk as well. If it doesn't exist in English, but in both bokmål and nynorsk, which to show?
Suggestion A2: We could let the user prioritize the languages (e.g. english 1, bokmål 2, nynorsk 3), and then just follow the list.
Suggestion A3: You are only allowed to check one extra language
Suggestion A4: Have a predetermined priorization of languages

Alternatively, there is a suggestion B:
(B) We could move the progress bar to the top of the lesson item, and have a collapsed dropdown (with a triangle) below the lesson title saying "Other languages:" and then show all the flags.  When uncollapsed, it would show a sublist of lessonitems for each of those languages (with the flag in front). Only show this if the lesson DOES exist in other languages, and only in those languages that have been checked.

If the lesson doesn't exist in the main language, we could:
Suggestion B2:  have the main language flag in the main lessonitem, but it would have to say "lesson does not exist <language>" or something, perhaps grayed out.
Suggestion B3: Same as B2, but with the collapsed list open for the lessons missing in the main language.
Suggestion B4: Don't have a lessonitem for the main language, only show the list (collapsed or open) for the lessons that have missing main language.

**Comment by NorwegianKiwi** [comment]
After thinking about the previous suggestions, I think that a variation of A4 is best. Explanation follows.

Suggestion: Display the lesson if it exists in the main language. If it doesn't exist in the main language, but exists in one of the other languages that have been checked in the filter, show the lesson in one of these languages instead, selected "randomly" (any language will do, whatever is easier code-wise). If a lesson doesn't exist in the main language or any of the checked languages, don't show the lesson at all.

Reasoning: We want to minimize choices people need to take, and we want to minimize clutter. When someone chooses a main language, they expect to find the lessons in this language, and if a lesson doesn't exist in the main language, showing the lessons in (one of) the other languages is just a backup. This should motivate to translate the lesson to the missing language.

By doing it this way, the user does not have to make any choices while viewing the lessons (only when choosing languages in the first place), and the course-page (playlist page) will be easier to read.

For the use case where a lesson author / translator wants to see which lessons are missing from a language (e.g. wants to see which lessons are missing from english), the just select English as the main language, and check all the other languages in the filter. Any lesson that then shows up without the english flag, needs to be translated.

**Comment by NorwegianKiwi** [comment]
It seems like we have to ask ourselves why the person checks the language filter boxes. E.g.:
a) Wishes to specify which fallback languages to show lessons in if the main language is missing (this is what I assumed above)
b) Wishes to specify languages so that all the lessons in all these languages are shown.

Both are valid reasons / uses cases, and implementing (b) is much simpler, since this is how it is now. We could of course do it differently for teacher and students, but this would quickly become confusing.

So, after being convinced by others, let's go for (b) in this issue. If (a) later seems to be needed as well, we could make a new issue, and then perhaps have a mode we could turn on to do this, a checkbox, button or similar. And if we later find out that we ONLY want (a), we can change the behavior.

Closing this issue.
