### ISSUE TITLE
Give user options when changing language inside a lesson

### ISSUE THREAD

**Issue by Skagevang** [kodeklubben/codeclub-viewer#287]
If a user change language when inside a lesson, and the lesson is not found on that language, there should be some options. Those could be: 
- Showing which language the same lesson could be done in
- Links/buttons to frontpage or playlistpage
- Improvepagebox comes up and encourage user to help with the translating

**Comment by tjesi** [comment]
I agree with the options. Two comments: 

- When you show which other languages the lesson could be done in, you should also link to the project in the other languages, to make it easy to find.
- I would prefer the playlist-page

**Comment by NorwegianKiwi** [comment]
Seems ok after merging #506.
