### ISSUE TITLE
Fix URL

### ISSUE THREAD

**Issue by Skagevang** [kodeklubben/codeclub-viewer#301]
Now the URL for a lesson e.g. Astrokatt, are /scratch/astrokatt/astrokatt. This should be changed to /scratch/astrokatt/nb if the lesson is in Norsk Bokmål. /scratch/astrokatt/en if the lesson is in English. etc.

**Comment by arve0** [comment]
Maybe /scratch/astrokatt should default/redirect/update url to selected language?

**Comment by NorwegianKiwi** [comment]
Closed, see PR #352 instead.
