### ISSUE TITLE
Show filter items in correct order

### ISSUE THREAD

**Issue by NorwegianKiwi** [kodeklubben/codeclub-viewer#314]
Currently, the order of the filter items is semi-random (the order they are read in from the lessons). We want at least some of the filters to always be in the same order, predetermined order, especially grades.

One suggestion is to have arrays for each group with valid tags in the order we want.

**Comment by NorwegianKiwi** [comment]
There is already a file in oppgave-repo named filtertags.md. Might as well use this to give the correct order.

**Comment by Skagevang** [comment]
Could create the right order in keys.md, but this will only be right for english. So my suggestion is adding this code to FilterGroup.js on line 36 :) 
`if (groupKey !== 'grade') {
      filterItems.sort((a, b) => {
        if (a.props.tagName < b.props.tagName) {
          return -1;
        }
        if (a.props.tagName > b.props.tagName) {
          return 1;
        }
        return 0;
      });
    }`
