### ISSUE TITLE
Tooltips for filtergroup and items

### ISSUE THREAD

**Issue by Skagevang** [kodeklubben/codeclub-viewer#318]
Use comments from [this file](https://github.com/kodeklubben/oppgaver/blob/master/src/filtertags.md) in tooltips

**Comment by NorwegianKiwi** [comment]
TOOLTIPS ligger nå i filene `https://github.com/kodeklubben/oppgaver/blob/master/filtertags/translation_xx.yml`, der `xx` er språket.
