### ISSUE TITLE
Checkboxes usynlige i {.try}

### ISSUE THREAD

**Issue by NorwegianKiwi** [kodeklubben/codeclub-viewer#339]
Dersom man har en seksjon med {.try}, så blir checkboxes inni her usynlige.

Et forslag er å bare bruke {.challenge}, men alternativt så kan man muligens endre bakgrunnsfargen i {.try}, eller endre fargen på checkboxes i {.try}.

**Comment by tjesi** [comment]
eg tenker at vi bare kan bytte ut {.try} med {.challenge}, da det uansett er tittelen i boksen som forklarer hva man skal gjøre der.

**Comment by Skagevang** [comment]
Da burde dette ligge som et issue i oppgaverepoet istedet
