### ISSUE TITLE
URL skal kun vise kurs og filnavn

### ISSUE THREAD

**Issue by NorwegianKiwi** [kodeklubben/codeclub-viewer#352]
På CC-viewer-sidene i dag består URL av kurs + mappenavn + filnavn, f.eks. "scratch/astrokatt/astrokatt" eller "scratch/astrokatt/astrokatt_nn".

Endre dette slik at det ikke står mappenavn, altså bare kurs + filnavn, f.eks. "scratch/astrokatt" eller "scratch/astrokatt_nn".

For å ikke ødelegge for eksterne sider som har lenker til "gamle siden", så må alle gamle url's rewrites til nye urls.

**Comment by Skagevang** [comment]
#301

**Comment by NorwegianKiwi** [comment]
Merk at fordi vi bruker filnavnet, og språket er tagget i YAML-headeren inni filen, så MÅ det ikke være _iso på slutten (f.eks. _nb og _en), men det oppfordres til det for å gjøre det mer oversiktlig.

**Comment by NorwegianKiwi** [comment]
I am starting to think this is not such a good idea. Perhaps it is better to keep the `courseName/lessonFolder/lessonFilename` url, perhaps even `courseName/lessonFolder/lessonFilename.md`.

There are three reasons I am thinking that we want to keep the lessonFolder in the url. One is so that it reflects the structure in oppgaverepo, and there are several lessons that refer to other lessons or resources in other lessons. By keeping the lessonFolder I believe it would be easier to make this relative urls work.

The other reason is that if we omit the lessonFolder from the URL, we have to make sure that NO lessonFiles have the same name! It might not be a huge problem, but suddenly one lessons starts overwriting another because someone came up with the same name in two different lesson folders.

The third reason is so that lesson-developers working only in oppgave-repo would find it easier to locate the files they want to change.

I think that the main reason this issue was reported, was because it seemed silly to have the same name repeated  e.g. `scratch/astrokatt/astrokatt`. This will be less of a "problem" when it starts being `scratch/astrokatt/astrokatt_nb`

Sidenote: If we add the file extension, `scratch/astrokatt/astrokatt.md` or `scratch/astrokatt/astrokatt_nb.md`, it becomes quite obvious that the last part is referring to a filename. Note that in the old pages it says `.html`, and we COULD use that, but strictly speaking it wouldn't be quite correct anymore, and again it would be easier to understand which file to change if we used `.md` (although the lessons will be "wrapped" in the lesson page with headers and footers etc, so it isn't quite true that it is only the "md"-file).

My suggestion: We keep it the way it is today, with `courseName/lessonFolder/lessonFile`, and without an extension. In order to accomodate for anybody that has saved old url's, we need to redirect from `lessonFile.html` to `lessonFile (which means we can stop remove `.html` from all urls in the lessonPages).

**Comment by gahjelle** [comment]
I agree that this has the possibility of introducing more problems than it seems to solve, and I agree with your suggestion.

Another way of addressing what I understand to be the original concern (URLs are uneccesarily long repeating the name of the project twice) would be if it is possible to automatically forward from the `courseName/lessonFolder` to the `courseName/lessonFolder/lessonFilename`-url. At least if we are moving to having only one lesson inside a folder this could work with some magic heuristics concerning the default language to show ... Again, it is not clear to me that this really solves much ...

**Comment by NorwegianKiwi** [comment]
Closing this issue, since we want to keep it like it is today, except do a rerouting, as covered by issue #386.
