### ISSUE TITLE
- [ ] tasks sometimes fail

### ISSUE THREAD

**Issue by arve0** [kodeklubben/codeclub-viewer#354]
See https://skagevang.github.io/beta/python/gjettelek/README/

![skjermbilde 2017-07-28 kl 08 26 49](https://user-images.githubusercontent.com/4810521/28705115-90bbd4a0-736e-11e7-9376-f789872c5049.png)

cc: @agnetedjupvik

**Comment by arve0** [comment]
Styling is a bit buggy too:

![skjermbilde 2017-07-28 kl 08 28 13](https://user-images.githubusercontent.com/4810521/28705151-c2d8c902-736e-11e7-9968-d96705ae1a9b.png)

**Comment by NorwegianKiwi** [comment]
Det ser ut som om problemet er at det er en del av mellomrommene i markdown-filene som er non-breaking spaces, altså char code 160 (non-breaking space) i stedet for 32 (vanlig space).

Dette forekommer bl.a. i følgende filer:
src/elm/04_input/04_input.md
src/python/repetisjon/README.md
src/web/ressurser/README_en.md (her forårsaker det nok ikke noe problem)
src/python/hemmelige_koder/README.md
src/python/skilpaddeskolen/README.md
src/python/lopende_strekmann/README.md
src/python/lister_og_indekser/README.md
src/python/gjettelek/README.md
src/python/hangman2/README.md

Løsningen bør være at checkbox-plugin tåler non-breaking spaces.

**Comment by NorwegianKiwi** [comment]
Har lagt inn issue her: https://github.com/linsir/markdown-it-task-checkbox/issues/8

**Comment by NorwegianKiwi** [comment]
I mellomtiden foreslår jeg at vi bare fjerner non-breaking spaces i oppgave-repoet.

**Comment by NorwegianKiwi** [comment]
Se også https://github.com/kodeklubben/oppgaver/issues/628

**Comment by NorwegianKiwi** [comment]
Flytter dette issuet til "version 2", men lar den være åpen i påvente av at linsir/markdown-it-task-checkbox#8 blir løst (planen er å sende inn en PR).

**Comment by NorwegianKiwi** [comment]
linsir/markdown-it-task-checkbox#8 er nå merged, så det som gjenstår burde være å oppdatere markdown-it-task-checkbox.
