### ISSUE TITLE
Remove numbers in filter

### ISSUE THREAD

**Issue by NorwegianKiwi** [kodeklubben/codeclub-viewer#361]
Each filter item now has a number of how many lessons is valid for each. It turns out this is for the most part confusing, and it seems better to just remove these alltogether. Also the code in the selectors in lesson.js are getting big and complicated. With the numbers removed, it is possible to make much simpler selectors. All that is needed is to calculate how many lessons are in each course. It might be useful to still show a filter item gray if there are no lessons left for it, but I don't think this is a "must".

**Comment by Skagevang** [comment]
I think it's a must to have grey filteritems if there is zero lessons available for that filteritem

**Comment by NorwegianKiwi** [comment]
We still need to remove dead code from the selectors before closing this issue.

**Comment by Skagevang** [comment]
Should this be a new issue for version 2? Clean up code regarding filternumbers and or-groups?

**Comment by Skagevang** [comment]
See #380
