### ISSUE TITLE
Upgrade scratchblocks library

### ISSUE THREAD

**Issue by NorwegianKiwi** [kodeklubben/codeclub-viewer#435]
When running `yarn`, the optional dependency for canvas in https://github.com/arve0/scratchblocks gives an ugly error in some OS'es (canvas is used to measure the size of fonts that are installed in the OS). Since the dependency is optional, the command still succeeds. But it would be nicer if it didn't show such an error.

First suggestion: Fork https://github.com/arve0/scratchblocks to https://github.com/kodeklubben/scratchblocks, and remove the optional dependencies.

But, as @arve0 mentions, a new project has started:
https://scratch.mit.edu/developers
https://developers.google.com/blockly/

Perhaps these can be used instead?

**Comment by arve0** [comment]
Adding some extra info. This really depends on why scratchblocks is included as a dependency and how it is used. `canvas` is a server-side dependency, which is needed if you use scratchblocks in node. If you use scratchblocks browser only, you should use the [official scratchblocks](https://github.com/scratchblocks/scratchblocks), not my fork.

**Comment by NorwegianKiwi** [comment]
If it makes it easier, perhaps don't render scratchblocks for the static pages, just show a "loading" spinner (or similar), and perhaps the "bare" text in the background. Then the webpage can render the "proper" scratch blocks when the javascript has been loaded.

**Comment by tjesi** [comment]
We also need to include support for extra languages. We have a lot of lessons in nynorsk (not supported) as well as bokmål (supported), and we expect to add several others in the future.

**Comment by NorwegianKiwi** [comment]
Upgraded to scratch3. The issue with canvas is still there, but that is because it is also in the official scratchblocks/scratchblocks. We could still fork it to kodeklubben and remove the node-part, but will make a separate issue of that.
