### ISSUE TITLE
Skille bokmål og nynorsk flagg

### ISSUE THREAD

**Issue by Skagevang** [kodeklubben/codeclub-viewer#471]
Hvis man går inn i scratch og har markert flere språk i filteret, kommer det flagg foran oppgaven. Men flaggene for bokmål og nynorsk er like. Foreløpig forslag er å legge til en B og N på flagget

**Comment by Skagevang** [comment]
Tror kanskje det er vanlig (standard) og ha en svart boks nede til høyre i flagget med en B for bokmål og N for nynorsk

**Comment by tjesi** [comment]
Det vanlige er å ha NB for bokmål og NN for nynorsk
