### ISSUE TITLE
Fix links in yarn start

### ISSUE THREAD

**Issue by Skagevang** [kodeklubben/codeclub-viewer#481]
When running yarn start, internal links in lessons that ends with .html will get an error. For example:
Cannot GET /web/hei_js/hei_js.html
It's the same if you write the the whole url for a lessons and it ends with .html

**Comment by Skagevang** [comment]
To reproduce: 
run yarn start
go to /web/grunnleggende_js/grunnleggende_js
click Hei JavaScript under Steg 1.

**Comment by NorwegianKiwi** [comment]
Tips: https://webpack.js.org/configuration/dev-server/#devserver-historyapifallback
I am guessing that when there is a "dot" in the url, it tries to serve the url directly, so perhaps `disableDotRule:true` is enough. Or perhaps we need to add some rewrites.
