### ISSUE TITLE
Fix MainLanguageButton for external lessons

### ISSUE THREAD

**Issue by Skagevang** [kodeklubben/codeclub-viewer#527]
If I go to https://oppgaver.kidsakoder.no/beta/microbit/python_hello_world/python_hello_world_nb with English as my GUI language, the MainLanguageButton says I can see the lesson in english. The problem is that the English version is an external lesson. If I click the button I'm sent to a page without a Lesson, just the title. I think there is two options:

1) Make the MainLanguageButton disabled and say that the Lesson is not on that language. As we do everywhere else.

2) Send the user to the external site for the lesson. 

I think options number one is the best

**Comment by tjesi** [comment]
I support your recommendation. We don't want to send people away from our side when changing language. We should aim to have all the lessons in markdown at our own page, and hence, in the long run have fewer and fewer external lessons.
