### ISSUE TITLE
URL ends with slash brakes the page

### ISSUE THREAD

**Issue by Skagevang** [kodeklubben/codeclub-viewer#529]
![image](https://user-images.githubusercontent.com/11090538/43356544-b3b17158-9272-11e8-960e-4324e6b0f9e3.png)

If the URL ends with a slash it first sends me to 404 then load the page with a wierd styling. This is not the case for the frontpage, but coursepages and lessonpages.

**Comment by NorwegianKiwi** [comment]
When going to `http://localhost:8080/scratch/veiledninger/kurs_avansert_scratch_plattform` when doing `yarn build` + `yarn serve`, we get a similar effect. Same bug?

**Comment by Skagevang** [comment]
In your example I get: Warning: Expected server HTML to contain a matching <span> in <div>.
