### ISSUE TITLE
Micro:bit blocks

### ISSUE THREAD

**Issue by steinoro** [kodeklubben/codeclub-viewer#543]
Code blocks for micro:bit programming should be available in the same way as for Scratch. Norsk bokmål and English for now, should also be ready for Norsk nynorsk when micro:bit supports both Norwegian languages.

**Comment by Skagevang** [comment]
Maybe we can use blockly?

https://developers.google.com/blockly/guides/get-started/web

**Comment by Skagevang** [comment]
https://jsfiddle.net/ndyz1d57/1/
