### ISSUE TITLE
Improve PDF rendering

### ISSUE THREAD

**Issue by Skagevang** [kodeklubben/codeclub-viewer#549]
Sometimes PDF rendering fails. Maybe try using https://www.npmjs.com/package/prerender or https://www.npmjs.com/package/chrome-render

**Comment by NorwegianKiwi** [comment]
Looked into it, and it wasn’t obvious. Also, the reason it crashed a lot was because it opened 300 tabs simultaneously. That bug has been fixed and we almost never see crashes. Closing this issue.
