### ISSUE TITLE
Create mock courses and mock lessons

### ISSUE THREAD

**Issue by kristandre** [kodeklubben/codeclub-viewer#84]
Lage noen fake kurs og oppgaver under `test/` for å kunne teste:
- [ ] getExternalCourses med courseContext
- [ ] getFilteredCourses med iconContext
- [ ] getLessons med lessonContext
- [ ] getTags med lessonContext
- [ ] getPlaylists med playlistContext

**Comment by NorwegianKiwi** [comment]
Gått ut på dato.
